[project]
name = "carro-financeiro"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "pandas",
    "requests",
    "pillow",
    "cachetools",
]
